### PR TITLE
use "$ref" for "schema" and "items"

### PR DESCRIPTION
**Pull request by shu-mutou**
Also, change test case.

### CODE REVIEW

**Comment by elmiko** [comment]
sorry Shu, taken me awhile to review this. it looks good, but i'm curious about how we will use the definitions stuff. i know how they are used in the openapi specs, but how will we support them from the code?

**Comment by shu-mutou** [comment]
Hi Mike, Thank you for your reply. The definitions stuff will be unnecessary, if the workflow from the source code to the API ref site HTML is going to be fully automated, I think. But now, we need to review the created swagger spec manually. Because the fully expanded swagger spec was too redundant to be reviewed, so I had improved.
The definitions stuff is added if the class for "schema" or "items" object does not inherit WSME classes. And they are distinguished by the class name.

**Comment by elmiko** [comment]
ok, thanks Shu. i'll look this over and get it merged soon.

**Comment by elmiko** [comment]
sorry for the delay Shu

**Comment by shu-mutou** [comment]
Thanks Mike! Could you increment the version number and upload to PYPI?

**Comment by elmiko** [comment]
yes, i'll try to publish 0.1.3 by the weekend

**Pull request merged**
